### ISSUE TITLE
Fix auth implementation and make hive tests pass.

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/ethereum_rust#343]
This can be tested by running: `just run-hive-debug ethereum/engine "engine-auth"` 

Currently, the jwt check is passing for every testcase, even for the case where the jwt token is invalid

**Comment by MarcosNicolau** [comment]
I've just run the suite on my machine! These 3 tests failing: 
- `JWT Authentication: Positive time drift, within limit, correct secret`
- `JWT Authentication: No time drift, correct secret`
- `JWT Authentication: Negative time drift, within limit, correct secret`

They are all failing for the same reason: this suite tests authentication by calling the `engine_exchangeTransitionConfigurationV1` method which we haven't implemented yet. So for those tests where the provided JWT is valid, it fails because we return `Method not found` err.  But the tests that should fail due to invalid auth (invalid token or IAT out of limit) do in fact pass. 

Since this test doesn't check for the validity of the returned values, we could:
- Edit the hive test and call another method on the engine API.
- Or implement the method: from what I understood, this method just compares the current `ChainConfig` with the one provided in the params so it shouldn't be hard.
