### ISSUE TITLE
Set the canonical chain head when receiving forkchoiceUpdates

### ISSUE THREAD

**Issue by mpaulucci** [lambdaclass/ethereum_rust#350]
This ticket assumes that there are no forks.

Depends on: https://github.com/lambdaclass/ethereum_rust/issues/244

Changes:
- When receiving a new payload, we should not set the new head or update the canonical chain, but instead just validate the payload and update the state trie (but the canonical state_root will not change since we don't update the head).
- When receiving a `forkchoiceUpdated` call, we should update the head (latest block number) and the canonical chain if it is valid (and the rest of the fields, like safe block).
- We should be able to store a block that is not canonical

**Comment by Arkenan** [comment]
I'm moving forward with the canonical chain representation, as part of this ticket. Our current db representation of the chain is done by the following tables, which have `BlockNumber` as a key:

- `BlockHeaders`
- `BlockBodies`
- `Receipts (+index). Esto es dupsort, ordena por index (seek value type?)`.
- `TransactionLocations (+index)`

We have two options:

### 1. Block Hash Indexing

Conceptually, all of those are properties of a block, so they are more correctly indexed by block hash instead of block number. If we change this, our canonical chain representation would be a table `BlockHashes`, which would map number to hash.

Pros:

- Implementation is simple and code reusable.
- When reorgs happen, changing the canonical chain only requires updating the `BlockHashes` table.

Cons:
- Reads to any of the 4 tables mentioned are 2 gets instead of one.

### 2. All tables are the canonical chain

If we want to prioritize read over write performance, we could, instead, keep tables as they are. The difference we would make is that when reorgs happen we would update the four tables, changing the receipt we are pointing to the new one.

Advantages:
- Faster reads (1 get instead of two).

Disadvantages:
- Slower and more complex writes. Not only because it's 4 writes instead of 1, but also because the full value is serialized and updated for each table (block body, receipts array, header and transaction locations array). Any of these is probably slower than updating the hash for the block number.
- We would probably still need the hash indexed tables so we can switch all tables to the new values using the block hash. This would also require an extra db read for each table.
- If we need the hash indexed tables too, this one is at least as difficult to implement as the other option.

**Comment by Arkenan** [comment]
We're going with the first idea! Created #403 to evaluate other indexing mechanisms

**Comment by Arkenan** [comment]
As an additional comment, by the end of the PR we're implementing now, this issue will support reorgs of 1 block, although at any point of the canonical chain. New issues have been open for more complex reorgs.
